# https://help.ubuntu.com/community/PowerManagement/ReducedPower

- name: Install power tools
  apt:
    pkg: ['powertop', 'pm-utils']
    update_cache: yes
    state: present
  become: true

- name: Turn on power saving
  command: pm-powersave true
  become: true
