# https://help.ubuntu.com/community/PowerManagement/ReducedPower

- name: Install power tools
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - powertop
    - pm-utils
  become: true

- name: Turn on power saving
  command: pm-powersave true
  become: true
