- name: Turn on remote login
  shell: systemsetup -setremotelogin on
  become: yes

- name: Create access_ssh group
  shell: dseditgroup -o create -q com.apple.access_ssh
  become: yes

- name: Add current user into access_ssh group
  shell: dseditgroup -o edit -a {{ ansible_user_id }}  -T group com.apple.access_ssh
  become: yes
