- name: Install ansible as a dependency
  hosts: all
  become: true
  roles:
    - FGtatsuro.ansible

- name: Restore my comphy laptop environment
  hosts: all
  become: true

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

    - name: Create the Workspace
      become: no
      file: path="{{ home_dir }}/Workspace" state=directory

    - name: Set monitor timeout
      shell: dbus-launch dconf write /org/gnome/desktop/session/idle-delay 600

    - name: Set screen lock
      shell: dbus-launch dconf write /org/gnome/desktop/screensaver/lock-enabled true

    - name: Set screen delay
      shell: dbus-launch dconf write /org/gnome/desktop/screensaver/lock-delay 1800

    - name: Install base applications.
      apt: pkg={{item}} update_cache=yes state=latest
      with_items:
        - adobe-flashplugin
        - glances

  roles:
    # tags: focus # ./focus.sh
    - role: roles/dnscrypt-proxy

    - role: roles/dropbox
      become: false

    - role: roles/ruby
      become: false

    - role: roles/bash-it
    - role: roles/flux
    - role: roles/git

    - role: roles/shortcuts
      become: false

    - role: roles/vim

    - role: ANXS.postgresql
      postgresql_version: 9.6
      postgresql_users:
        - name: "{{ lookup('env','USER') }}"
      postgresql_user_privileges:
        - name: "{{ lookup('env','USER') }}"
          priv: "ALL"
          db: postgres
          role_attr_flags: "CREATEDB"
      postgresql_ext_install_dev_headers: yes

    - role: FGtatsuro.vagrant
    - role: bearandgiraffe.heroku-cli
    - role: cmprescott.chrome
    - role: iknite.spotify

