- include: base.yml

- name: Restore my comphy laptop environment
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"
    shared_dir: "/mnt/Shared"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh

    - role: roles/flux
    - role: roles/shortcuts
    - role: roles/settings-power

    # This is just too flaky to run on it's own
    # because of the automount and other issues
    - role: roles/dropbox

    - role: roles/spotify
      become: true

    - role: roles/ruby
      become: true

    - role: rdeknijf.chromedriver
      become: true

    - role: bearandgiraffe.heroku-cli
      become: true

    - role: ANXS.postgresql
      postgresql_version: 9.6
      postgresql_users:
        - name: "{{ lookup('env','USER') }}"
      postgresql_user_privileges:
        - name: "{{ lookup('env','USER') }}"
          priv: "ALL"
          db: postgres
          role_attr_flags: "CREATEDB"
      postgresql_ext_install_dev_headers: yes
      become: true

    - role: jpnewman.redis
      become: true

