- src: ANXS.postgresql
- src: FGtatsuro.python-requirements
- src: FGtatsuro.virtualbox
- src: FGtatsuro.vagrant
- src: cmprescott.chrome
- src: ferrarimarco.chruby
- src: ferrarimarco.ruby-install
- src: haxorof.docker-ce
- src: jpnewman.redis

- src: juju4.dnscrypt-proxy
  version: master

- src: rdeknijf.chromedriver
- src: wtanaka.dropbox
