- src: ANXS.postgresql
- src: FGtatsuro.python-requirements
- src: FGtatsuro.vagrant
# - src: bearandgiraffe.heroku-cli
- src: cmprescott.chrome
- src: ferrarimarco.chruby
- src: ferrarimarco.ruby-install
- src: haxorof.docker-ce
- src: jpnewman.redis
- src: juju4.dnscrypt-proxy
- src: rdeknijf.chromedriver
- src: wtanaka.dropbox
