- src: geerlingguy.homebrew
- src: ANXS.postgresql
- src: FGtatsuro.python-requirements
- src: andrewrothstein.vagrant
- src: Oefenweb.virtualbox
- src: Oefenweb.dropbox
- src: cmprescott.chrome
- src: ferrarimarco.chruby
- src: ferrarimarco.ruby-install
- src: rdeknijf.chromedriver
- src: ansiblebit.oracle-java
- src: nickpack.android_sdk
- src: gantsign.intellij

- src: dhellmann.python-dev
  version: master
