- name: Test Engineers Workstations/Jenkins Agent
  hosts: all
  remote_user: "{{ remote_user }}"

  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

  vars:
    mas_installed_apps:
      - { id: 497799835, name: "Xcode" }
    homebrew_taps:
      - homebrew/cask
      - homebrew/cask-versions
      - facebook/fb
    homebrew_installed_packages:
      - ssh-copy-id
      - ansible
      - carthage
      - git
      - mg
      #- { name: fbsimctl, install_options: "HEAD" }
      #- { name: gnu-sed, install_options: "default-names" }
      - ios-webkit-debug-proxy
      - imagemagick
      - libimobiledevice
      - maven
      - wget
      - bash-completion
      - name: python@2
      - { name: python@3, install_options: "tcl-tk" }
      - tcl-tk
      - zlib
    homebrew_uninstalled_packages:
      - node
      - nvm
    homebrew_cask_apps:
      - google-chrome
      - chromedriver
      - java8
      # - fastlane
      # - teamviewer


  roles:
    - geerlingguy.homebrew
    - role: nvm
      version: 'v0.34.0'
    - role: node
      version: '11.13.0'
    - role: appium
      version: '1.12.1'
    - macos/remote-login
    - macos/remote-management-add


  tasks:
    - name: Speed up ssh connection
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        create: yes
        block: |
          HOST *
          CONTROLMASTER auto
          CONTROLPATH /tmp/ssh-%r@%h:%p
          AddressFamily inet
          ServerAliveInterval 80

    - name: Ensure Workspace exists
      file:
        path: "{{ ansible_env.HOME }}/Workspace"
        state: directory
        mode: 0775

    - name: Ensure jenkins root dir exists
      file:
        path: "{{ ansible_env.HOME }}/Workspace/jenkins"
        state: directory
        mode: 0775

    - name: Install virtualenv for python@2
      shell: pip install virtualenv

    - name: Install xcode-install
      gem:
        name: xcode-install
        state: present
