- import_playbook: base.yml


- name: Some useful stuff for a TE workstation
  hosts: all
  remote_user: woi


  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh test-engineering.yml

    - role: rdeknijf.chromedriver
      become: true
    - role: dhellmann.python-dev
      python_dev_versions:
        - version: "2.7"
        - version: "3.7"
      python_dev_install_pypy: false

    - role: ansiblebit.oracle-java
      oracle_java_use_defaults: no
      oracle_java_apt_repository: "ppa:webupd8team/java"
      oracle_java_cache_valid_time: 3600
      oracle_java_deb_package: 'oracle-java8-installer'
      oracle_java_debconf_package_default: 'oracle-java8-set-default'
      oracle_java_home: "/usr/lib/jvm/java-8-oracle"
      oracle_java_license_version: "shared/accepted-oracle-license-v1-1"
      oracle_java_set_as_default: no
      oracle_java_state: latest

    - role: Oefenweb.virtualbox
      become: true

    - role: android-sdk
      username: woi
    - role: genymotion
      version: "3.0.1"
      download_location: "/opt/android"
      install_location: "/opt/android"

    - role: nvm
      version: 'v0.34.0'
    - role: node
      version: '11.11.0'
    - role: appium
      version: '1.11.1'

  tasks:
    - name: Install packages required for TE nodes
      apt:
        pkg: ['python-tk', 'build-essential', 'libglu1', 'firefox', 'htop', 'xvfb']
        state: present
        update_cache: yes
      become: yes

    - name: Speed up ssh connection
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        create: yes
        block: |
          HOST *
          CONTROLMASTER auto
          CONTROLPATH /tmp/ssh-%r@%h:%p
          AddressFamily inet
          ServerAliveInterval 80

    - name: Ensure Workspace exists
      file:
        path: "{{ ansible_env.HOME }}/Workspace"
        state: directory
        mode: 0775

    - name: Ensure jenkins root dir exists
      file:
        path: "{{ ansible_env.HOME }}/Workspace/jenkins"
        state: directory
        mode: 0775

    - name: Install virtualenv for python@2
      shell: pip2 install virtualenv
      become: yes