- include: base.yml

- name: Some useful stuff for a TE workstation
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"
    chromedriver_version: 2.33

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

    - name: Install base applications.
      apt:
        pkg: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - glances
        - compizconfig-settings-manager
      become: true

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh test-engineering.yml

    # terminator

    - role: atom
    - role: robotframework
    - role: rdeknijf.chromedriver
      become: true

