- import_playbook: base.yml

- name: Some useful stuff for a TE workstation
  hosts: all

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh test-engineering.yml

    - role: Oefenweb.virtualbox
      become: true

    - role: rdeknijf.chromedriver
      become: true

    - role: dhellmann.python-dev
      python_dev_versions:
        - version: "2.7"
        - version: "3.7"
      python_dev_install_pypy: false

    - role: genymotion
      android_home: "{{ ansible_env.HOME }}/android"

    - role: nickpack.android_sdk
      vars_files:
        - vars/te_android.yml
      become: true

    - role: ansiblebit.oracle-java
      oracle_java_use_defaults: no
      oracle_java_apt_repository: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu bionic main'
      oracle_java_apt_repository_key: 'EA8CACC073C3DB2A'
      oracle_java_cache_valid_time: 3600
      oracle_java_deb_package: 'oracle-java8-installer'
      oracle_java_debconf_package_default: 'oracle-java8-set-default'
      oracle_java_home: "/usr/lib/jvm/java-8-oracle"
      oracle_java_license_version: "shared/accepted-oracle-license-v1-1"
      oracle_java_set_as_default: no
      oracle_java_state: present

    - role: nvm
      version: 'v0.33.11'
    - role: node
      version: '8.12.0'
    - role: appium
      version: '1.10.0'
