- import_playbook: base.yml

- name: Some useful stuff for a TE workstation
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"
    chromedriver_version: 2.33

  tasks:
    - name: Install base applications.
      apt:
        pkg: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - glances
      become: true

    - name: Add Android SDK business to the bashrc
      blockinfile:
        path: "{{ home_dir }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Android"
        content: |
          export ANDROID_HOME=/opt/android-sdk-linux
          export ANDROID_SDK=$ANDROID_HOME
          PATH=$PATH:$ANDROID_HOME/build-tools
          PATH=$PATH:$ANDROID_HOME/platform-tools
          PATH=$PATH:$ANDROID_HOME/tools
          PATH=$PATH:$ANDROID_HOME/tools/bin
          export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
          export PATH=$JAVA_HOME/bin:$PATH

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh test-engineering.yml

    - role: nickpack.android_sdk
      become: true

    - role: gantsign.intellij

    - role: rdeknijf.chromedriver
      become: true
    - { role: dhellmann.python-dev, python_dev_versions: [{version: "2.7"}], python_dev_install_pypy: false }
    - { role: nvm, version: 'v0.33.11' }
    - { role: node, version: '8.12.0' }
    - { role: appium, version: '1.9.1' }
