- name: Test Engineers Workstations/Jenkins Agent
  hosts: all
  remote_user: "{{ remote_user }}"

  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

  vars:
    user: "{{ remote_user }}"
    mas_installed_apps:
      - { id: 497799835, name: "Xcode" }
    homebrew_taps:
      - homebrew/cask
    homebrew_installed_packages:
      - ssh-copy-id
      - ansible
      - git
      - wget
      - bash-completion
      - { name: python@2, install_options: "--with-tcl-tk" }
      - { name: python@3, install_options: "--with-tcl-tk" }
      - zlib
    homebrew_uninstalled_packages:
      - node
      - nvm
    homebrew_cask_apps:
      - teamviewer

  roles:
    - geerlingguy.homebrew
    - { role: nvm, version: 'v0.33.11' }
    - node
    - { role: appium, version: '1.8.1' }
    - geerlingguy.mas


  tasks:
    - name: Ensure Workspace exists
      file:
        path: "{{ ansible_env.HOME }}/Workspace"
        state: directory
        mode: 0775

    - name: Install virtualenv for python@2
      shell: pip install virtualenv

