- include: workstation.yml

- name: Restore my comphy laptop environment
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh tommy.yml

    - role: dnscrypt-proxy
      ignore_errors: true

    - role: dropbox
      become: true

    # Ubuntu 18.04 ships with 2.5.1, so no need for chruby just yet (take a long time to install anyway)
    - role: roles/ruby
      become: true

    - role: heroku-cli
    - role: shortcuts-tommy
    - role: spotify

    - role: touchpad
      when: laptop is defined

    - role: settings-power
      when: laptop is defined

