- include: workstation.yml

- name: Restore my comphy laptop environment
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"
    shared_dir: "/mnt/Shared"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh tommy.yml

    - role: roles/dnscrypt-proxy
    - role: roles/flux
    - role: roles/settings-power
    - role: roles/shortcuts-tommy
    - role: roles/touchpad

    - role: roles/dropbox
      become: true

    - role: roles/spotify
      become: true
