- include: base.yml

- name: Some useful stuff for a workstation
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh workstation.yml

    # Ubuntu 18.04 ships with 2.5.1, so no need for chruby just yet (take a long time to install anyway)
    # - role: roles/ruby
    #   become: true

    - role: rdeknijf.chromedriver
      become: true

    - role: roles/heroku-cli
      become: true

    - role: ANXS.postgresql
      postgresql_version: 9.6
      postgresql_users:
        - name: "{{ lookup('env','USER') }}"
      postgresql_user_privileges:
        - name: "{{ lookup('env','USER') }}"
          priv: "ALL"
          db: postgres
          role_attr_flags: "CREATEDB"
      postgresql_ext_install_dev_headers: yes
      become: true

    - role: FGtatsuro.vagrant
      become: true

    - role: roles/yubikey
      become: true

    - role: ocs-agent
      become: true
      when: ocs_server is defined
