- include: base.yml

- name: Some useful stuff for a workstation
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh workstation.yml

    - role: roles/ruby
      become: true

    - role: rdeknijf.chromedriver
      become: true

    - role: roles/heroku-cli
      become: true

    # - role: haxorof.docker-ce
    #   become: true

    - role: ANXS.postgresql
      postgresql_version: 9.6
      postgresql_users:
        - name: "{{ lookup('env','USER') }}"
      postgresql_user_privileges:
        - name: "{{ lookup('env','USER') }}"
          priv: "ALL"
          db: postgres
          role_attr_flags: "CREATEDB"
      postgresql_ext_install_dev_headers: yes
      become: true

    # - role: jpnewman.redis
    #   become: true

    # on 17.04 this role can't find virutalbox 5.1 somehow messed up,
    # let's stick with 16.04 for now
    # - role: FGtatsuro.vagrant
    #  become: true

    # - role: roles/yubikey

    - role: ocs-agent
      become: true
      when: ocs_server is defined
