#- import_playbook: base.yml

- name: Some useful stuff for a workstation
  hosts: all

  vars:
    home_dir: "/home/{{ lookup('env','USER') }}"

  tasks:
    - name: Show me the home dir
      shell: echo {{ home_dir }}

    - name: Install base applications.
      apt:
        pkg: ['python3-dev', 'python3-pip', 'indicator-multiload', 'compizconfig-settings-manager']
        update_cache: yes
        state: present
      become: true

  roles:
    # - debug: msg={{ variable }}
    # tags: focus # ./focus.sh workstation.yml

    #- role: ruby
    #  become: true

    - role: git-pair
      become: true

    #- role: rdeknijf.chromedriver
    #  become: true

    #- role: andrewrothstein.vagrant
    #  become: true

    #- role: Oefenweb.virtualbox
    #  become: true

    #- role: ANXS.postgresql
    #  postgresql_version: 10
    #  postgresql_users:
    #    - name: "{{ lookup('env','USER') }}"
    #  postgresql_user_privileges:
    #    - name: "{{ lookup('env','USER') }}"
    #      priv: "ALL"
    #      db: postgres
    #      role_attr_flags: "CREATEDB"
    #  postgresql_ext_install_dev_headers: yes
    #  become: true

    #- role: google-cloud-sdk
    #  become: true

    #- role: yubikey

    #- role: ocs-agent
    #  become: true
    #  when: ocs_server is defined
