#!/usr/bin/env bash

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='minimal'
# Tommy approved themes: sexy, sirup, rainbowbrite, bakke, minimal, nwinkler

# Set the global default editor, used for things like `git rebase -i`
export EDITOR=vim
export GIT_EDITOR=vim

# Don't check mail when opening terminal.
unset MAILCHECK

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Load Bash It
source $BASH_IT/bash_it.sh
source $HOME/.secrets

# Ignore gvim errors
alias gvim="gvim 2>/dev/null"
alias mvim="gvim 2>/dev/null"

# Tommy's natrual scrolling
  device=$(xinput list --id-only 'Razer  Razer Abyssus')
  xinput set-prop $device 280 -1, -1, -1

# Ata & Ardan's keyboard aliases
  alias x='xinput --list'

  colemak(){
    setxkbmap -device $1 -layout us -variant colemak -option caps:backspace
  }
  alias c=colemak

  dvorak(){
    setxkbmap -device $1 -layout us -variant dvorak
  }
  alias d=dvorak

  qwerty(){
    setxkbmap -device $1 -layout us
  }
  alias qa='setxkbmap -layout us' # Always available to get you back to Query
  alias q=qwerty

