#!/usr/bin/env bash

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='minimal'
# Tommy approved themes: sexy, sirup, rainbowbrite, bakke, minimal, nwinkler

# Set the global default editor, used for things like `git rebase -i`
# might not be necessary with bash-it-plugin edit-mode-vi
export EDITOR=vim
export GIT_EDITOR=vim

# Don't check mail when opening terminal.
unset MAILCHECK

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Load Bash It
source "$BASH_IT"/bash_it.sh

# while the `bash-it enable completion system` is still broken in 18.04
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

alias gitg="gitg &>/dev/null"
alias gvim="gvim &>/dev/null"
alias mvim="gvim &>/dev/null"

open() {
  gnome-open $1 &>/dev/null
}

# Ata's keyboard aliases
  alias x='xinput --list'

  colemak(){
    setxkbmap -device $1 -layout us -variant colemak -option caps:backspace
  }
  alias c=colemak

  dvorak(){
    setxkbmap -device $1 -layout us -variant dvorak
  }
  alias d=dvorak

  qwerty(){
    setxkbmap -device $1 -layout us
  }
  alias qa='setxkbmap -layout us' # Always available to get you back to Query
  alias q=qwerty

# Natrual Scrolling
  natural-scrolling() {
    local device_id
    printf "Devices:"
    xinput list
    printf "\n\n"
    read -p "Device Id: " device_id
    xinput set-prop $device_id 280 -1, -1, -1
    printf "\n"
  }
