# wget -q -O -  | sudo apt-key add -
# apt-key adv --keyserver pgp.mit.edu --recv-keys 1AD28806
#
# sudo sh -c 'echo deb https://www.charlesproxy.com/packages/apt/ charles-proxy main > /etc/apt/sources.list.d/charles.list'

- name: Get the Charles Proxy key 
  shell: wget --quiet -O - https://www.charlesproxy.com/packages/apt/PublicKey | sudo apt-key add -

- name: Adds repo Charles Proxy
  apt_repository:
    repo: ""
    state: present
  become: true

- name: Install Charles Proxy
  apt:
    name: charles-proxy
    state: present
    update_cache: yes
  become: true
