- name: Adds the copyq repo
  apt_repository:
    repo: ppa:hluk/copyq
    state: present
  become: true

- name: Install copyq
  apt:
    name: copyq
    state: present
  become: true

- name: Create the custom keyboard shortcut
  shell: "\t\tGo to: All Settings > Keyboard > Shortcuts and add name: CopyQ, command: copyq toggle, launcher: Shift+Ctrl+V"

