
- name: install google cloud apt repository key
  apt_key:
    id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
    keyring: /etc/apt/trusted.gpg.d/google-cloud.gpg
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: install google cloud apt repository
  apt_repository:
    repo: deb http://packages.cloud.google.com/apt cloud-sdk-bionic main
    filename: google-cloud
    update_cache: true

- name: refresh apt cache
  apt:
    update_cache: yes

- name: install google cloud sdk
  package:
    name: google-cloud-sdk
    state: present
