- name: Add the Spotify repository signing keys to be able to verify downloaded packages
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: "{{ item }}"
  with_items:
    - BBEBDCB318AD50EC6865090613B00F1FD2C19886
    - 0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: Add the Spotify repository
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    update_cache: yes

- name: Install Spotify
  apt:
    name: spotify-client
    state: latest
