- name: Add the Spotify repository signing keys to be able to verify downloaded packages
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
  become: true

- name: Add the Spotify repository
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    update_cache: yes
  become: true

- name: Install Spotify
  apt:
    name: spotify-client
    state: latest
  become: true
