- name: Adds repo Atom
  apt_repository:
    repo: ppa:webupd8team/atom
    state: present
  become: true

- name: Install Atom Text Editor
  apt:
    name: atom
    state: latest
    update_cache: yes
  become: true
