- name: Download genymotion
  get_url:
    url:  https://dl.genymotion.com/releases/genymotion-{{ version }}/genymotion-{{ version }}-linux_x64.bin
    dest: "{{ download_location }}/genymotion-{{ version }}-linux_x64.bin"
    mode: 0755
  become: yes

- name: execute genymotion
  shell: echo y| {{ download_location }}/genymotion-{{ version }}-linux_x64.bin -d {{ install_location }}
  become: yes

- name: Add genymotion to system-wide $PATH.
  copy:
    dest: /etc/profile.d/genymotion-path.sh
    content: 'PATH=$PATH:{{ install_location }}'
  become: yes