- name: Remove unnecessary examples link
  file:
    path: "{{ home_dir }}/examples.desktop"
    state: absent

# This isn't working, even with `dbus-launch` and sudo, no go.
# must google more.
#
# - name: Remove silly locked items from launcher
#   shell: dbus-launch gsettings set com.canonical.Unity.Launcher favorites "[ 'application://org.gnome.Nautilus.desktop', 'application://google-chrome.desktop', 'application://gnome-terminal.desktop', 'application://spotify.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices' ]"
#   become: true
#
# - name: Default shortcuts in dash, just for reference
#   shell: gsettings set com.canonical.Unity.Launcher favorites "[ 'application://org.gnome.Nautilus.desktop', 'application://firefox.desktop', 'application://libreoffice-writer.desktop', 'application://libreoffice-calc.desktop', 'application://libreoffice-impress.desktop', 'application://org.gnome.Software.desktop', 'application://ubuntu-amazon-default.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices' ]"
#
#
