---

- name: Install packages required by our Vim Config
  apt: pkg={{item}} state=present
  with_items:
    - git
    - vim
    - vim-gnome
    - ruby
    - ruby-dev
    - rake
    - exuberant-ctags
    - silversearcher-ag
  become: true

- name: Checkout pretty fonts
  git: repo=git://github.com/powerline/fonts
       dest="{{ home_dir }}/.fonts"
       depth=1
       update=true
       accept_hostkey=yes

- name: Install pretty fonts
  command: "{{ home_dir }}/.fonts/install.sh"

- name: Checkout our Vim Config
  git: repo=git://github.com/kmk-online/vim-config.git
       dest="{{ home_dir }}/.vim-config"
       depth=1
       update=true
       accept_hostkey=yes

- name: Initialize vim config
  command: "{{ home_dir }}/.vim-config/install.sh"
