---

- name: Install packages required by our Vim Config
  apt: pkg={{item}} state=present
  with_items:
    - git
    - vim
    - vim-gnome
    - ruby
    - ruby-dev
    - rake
    - exuberant-ctags
    - silversearcher-ag
  become: true

- name: Checkout pretty fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ home_dir }}/.fonts"
    update: yes
    accept_hostkey: yes

- name: Install pretty fonts
  command: "{{ home_dir }}/.fonts/install.sh"

- name: Checkout our Vim Config
  git:
    repo: https://github.com/KMK-ONLINE/vim-config.git
    dest: "{{ home_dir }}/.vim-config"
    update: yes
    accept_hostkey: yes

- name: Initialize vim config
  command: "{{ home_dir }}/.vim-config/install.sh"
