- name: Install the other Ruby development dependencies, mostly used by gems
  # https://github.com/postmodern/chruby/wiki/Ruby
  apt: name={{item}} state=present
  with_items:
    - bison
    - build-essential
    - cmake
    - libffi-dev
    - libgdbm-dev
    - libqt5webkit5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - qt5-default
    - zlib1g-dev
  become: true

- name: Fetch the latest rubies
  command: ruby-install --latest
  become: false

- name: Check installed rubies
  command: ls {{ home_dir }}/.rubies
  register: rubies

- name: Install ruby 2.4.0
  command: ruby-install ruby 2.4.0
  become: false
  when: rubies.stdout.find('2.4.0') == -1

- name: Install ruby 2.4.1
  command: ruby-install ruby 2.4.1
  become: false
  when: rubies.stdout.find('2.4.1') == -1

- name: Update our .gemrc
  copy: src=gemrc dest="{{ home_dir }}/.gemrc"
