- name: Install the other Ruby development dependencies, mostly used by gems
  # https://github.com/postmodern/chruby/wiki/Ruby
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - bison
    - build-essential
    - cmake
    - libffi-dev
    - libgdbm-dev
    - libqt5webkit5-dev
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - qt5-default
    - zlib1g-dev
  become: true

- name: Update our .gemrc
  copy:
    src: gemrc
    dest: "{{ home_dir }}/.gemrc"

- name: Update our .irbrc
  copy:
    src: irbrc
    dest: "{{ home_dir }}/.irbrc"

- name: Fetch the latest rubies
  command: ruby-install --latest
  become: false

- name: Check installed rubies
  command: ls {{ home_dir }}/.rubies
  register: rubies
  ignore_errors: true

- name: Install ruby 2.5.1
  command: ruby-install ruby 2.5.1
  become: false
  when: rubies.stdout.find('2.5.1') == -1
